# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: /login
                check_path: /login_check
                use_referer: true
                default_target_path: /profile
                always_use_default_target_path: false
            logout:       
                path: /logout
                target: /
            anonymous: ~

    role_hierarchy:
        ROLE_RECRUITER:   ROLE_USER
        ROLE_ADMIN:       ROLE_RECRUITER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_RECRUITER]

    encoders:
         FOS\UserBundle\Model\UserInterface:
            algorithm: bcrypt
            cost: 12
    
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/CV, roles: ROLE_RECRUITER }
        - { path: ^/Blog/AddBlog, roles: ROLE_ADMIN }
        - { path: ^/Blog/edit/, roles: ROLE_ADMIN }

